class BreedModel {
  String breedName;
  bool isSelected;
  String category;

  BreedModel({this.breedName, this.isSelected, this.category});
}

final List<BreedModel> breedModel = [
  BreedModel(
      breedName: "Afador", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Affenhuahua", isSelected: false, category: "Dog"),
  BreedModel(
      breedName: "Affenpinscher", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Afghan Hound", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Airedale Terrier", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Akbash", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Akita", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Akita Chow", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Akita Pit", isSelected: false, category: "Dog"),
  BreedModel(breedName: "American Staffordshire Terrier", isSelected: false, category: "Dog"),
  BreedModel(breedName: "American Water Spaniel", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Anatolian Shepherd Dog", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Appenzeller Sennenhunde", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Auggie", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Aussiedoodle", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Aussiepom", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Australian Cattle Dog", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Australian Kelpie", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Australian Retriever", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Australian Shepherd", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Australian Shepherd Husky", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Australian Shepherd Lab Mix", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Australian Shepherd Pit Bull Mix", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Australian Stumpy Tail Cattle Dog", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Australian Terrier", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Azawakh", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Barbet", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Basenji", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Bassador", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Basset Fauve de Bretagne", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Basset Hound", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Basset Retriever", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Bavarian Mountain Scent Hound", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Beabull", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Beagle", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Beaglier", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Bearded Collie", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Bedlington Terrier", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Belgian Malinois", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Belgian Sheepdog", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Belgian Tervuren", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Bergamasco Sheepdog", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Berger Picard", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Bernedoodle", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Bernese Mountain Dog", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Bichon Frise", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Biewer Terrier", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Black and Tan Coonhound", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Black Mouth Cur", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Black Russian Terrier", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Bloodhound", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Blue Lacy", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Bluetick Coonhound", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Bocker", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Boerboel", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Boglen Terrier", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Bohemian Shepherd", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Bolognese", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Borador", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Border Collie", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Border Sheepdog", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Border Terrier", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Bordoodle", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Borzoi", isSelected: false, category: "Dog"),
  BreedModel(breedName: "BoShih", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Bossie", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Boston Boxer", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Boston Terrier", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Boston Terrier Pekingese Mix", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Bouvier des Flandres", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Boxador", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Boxer", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Boxerdoodle", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Boxmatian", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Boxweiler", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Boykin Spaniel", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Bracco Italiano", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Braque du Bourbonnais", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Briard", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Brittany", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Broholmer", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Brussels Griffon", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Bugg", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Bull-Pei", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Bull Terrier", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Bullador", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Bullboxer Pit", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Bulldog", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Bullmastiff", isSelected: false, category: "Dog"),
  BreedModel(breedName: "Bullmatian", isSelected: false, category: "Dog"),
  //-------------------------------------------------------------------------------//
  BreedModel(
      breedName: "British Shorthair", isSelected: false, category: "Cat"),
  BreedModel(breedName: "Persian Cats", isSelected: false, category: "Cat"),
  BreedModel(breedName: "Maine Coon Cats", isSelected: false, category: "Cat"),
  BreedModel(
      breedName: "American Shorthair", isSelected: false, category: "Cat"),
  BreedModel(
      breedName: "Scottish Fold Cats", isSelected: false, category: "Cat"),
  BreedModel(breedName: "Sphynx Cats", isSelected: false, category: "Cat"),
  //-------------------------------------------------------------------------------//

  BreedModel(breedName: "Budgies", isSelected: false, category: "Bird"),
  BreedModel(breedName: "Cockatiels", isSelected: false, category: "Bird"),
  BreedModel(breedName: "Peach Faced", isSelected: false, category: "Bird"),
  BreedModel(breedName: "Parrotlets", isSelected: false, category: "Bird"),
  BreedModel(breedName: "Hyacinth Macaws", isSelected: false, category: "Bird"),
  BreedModel(breedName: "Canaries", isSelected: false, category: "Bird"),
  BreedModel(breedName: "Finches", isSelected: false, category: "Bird"),
  //-------------------------------------------------------------------------------//

  BreedModel(breedName: "other0", isSelected: false, category: "Others"),
  BreedModel(breedName: "other1", isSelected: false, category: "Others"),
  BreedModel(breedName: "other2", isSelected: false, category: "Others"),
];
